# Generated by Django 4.1.1 on 2022-09-28 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_reference_id', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('currency', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('customer_creation', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(max_length=255)),
                ('session_id', models.TextField()),
                ('livemode', models.BooleanField()),
                ('mode', models.CharField(max_length=255)),
                ('session_object', models.CharField(max_length=255)),
                ('payment_intent', models.CharField(max_length=255)),
                ('payment_link', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('setup_intent', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('submit_type', models.CharField(max_length=255)),
                ('subscription', models.CharField(max_length=255)),
                ('success_url', models.TextField()),
                ('cancel_url', models.TextField()),
                ('url', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_reference_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('tax_exempt', models.CharField(max_length=255)),
                ('costumer_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('line1', models.CharField(max_length=255)),
                ('lin2', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.customerdetails')),
            ],
        ),
    ]
