# Generated by Django 4.1.1 on 2022-09-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='lin2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='line1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='tax_exempt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client_reference_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='currency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='customer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='customer_creation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='customer_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='payment_intent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='payment_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='payment_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_object',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='setup_intent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='submit_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='subscription',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
