# Generated by Django 4.1.1 on 2022-09-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customeraddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='cancel_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='success_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
