# Generated by Django 4.1.1 on 2022-09-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_session_cancel_url_alter_session_success_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='costumer_details',
            new_name='customer_details',
        ),
    ]
